USE [master]
GO

/****** Object:  Database [PointofSalesSystem]    Script Date: 9/8/2015 12:15:22 PM ******/
CREATE DATABASE [PointofSalesSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PointofSalesSystem', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\PointofSalesSystem.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PointofSalesSystem_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\PointofSalesSystem_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PointofSalesSystem] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PointofSalesSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PointofSalesSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PointofSalesSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PointofSalesSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PointofSalesSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PointofSalesSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PointofSalesSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PointofSalesSystem] SET  MULTI_USER 
GO

ALTER DATABASE [PointofSalesSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PointofSalesSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PointofSalesSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PointofSalesSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PointofSalesSystem] SET  READ_WRITE 
GO

